---

- name: Ensure ansible directories exist
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ win_temp_dir }}"
    - "{{ win_log_dir }}"

- name: Import windows-firewall
  ansible.builtin.import_tasks: windows-firewall.yml
  when: win_config == 'rule'

- name: Import windows-firewall-import
  ansible.builtin.import_tasks: windows-firewall-import.yml
  when: win_config == 'import'
